### ISSUE TITLE
Potential Aliasses

### ISSUE THREAD

**Issue by FireController1847** [TeamVK/PAPI-RandomNumber#1]
Howdy!

I'm having an issue using this. It works perfectly for what I need (returning a double), however... I am using it in an environment where a non-double RNG expansion is being registered by a separate plugin. It is parsing for "%random_min_max%". This causes an error when I try doing "%random_number_min_max%" as it will attempt to parse the word "number" instead of using this expansion.

Are there any aliasses this expansion registers that I can't figure out? It'd be super helpful! Maybe also registering for "%rng_min_max" and "%randomnumber_min_max%" would be super helpful!

**Comment by vk2gpz** [comment]
use the 1.1.0
